# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 20, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_IP.setGeometry(QtCore.QRect(70, 20, 131, 20))
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 54, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Gateway = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Gateway.setGeometry(QtCore.QRect(70, 80, 131, 20))
        self.lineEdit_Gateway.setObjectName("lineEdit_Gateway")
        self.checkBox_Ssh = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Ssh.setGeometry(QtCore.QRect(440, 110, 41, 21))
        self.checkBox_Ssh.setChecked(True)
        self.checkBox_Ssh.setObjectName("checkBox_Ssh")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 210, 541, 171))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 110, 54, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 80, 51, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_UplinkPort = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_UplinkPort.setGeometry(QtCore.QRect(290, 80, 61, 20))
        self.lineEdit_UplinkPort.setObjectName("lineEdit_UplinkPort")
        self.pushButton_AddSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddSwitch.setGeometry(QtCore.QRect(560, 210, 91, 23))
        self.pushButton_AddSwitch.setObjectName("pushButton_AddSwitch")
        self.pushButton_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Generate.setGeometry(QtCore.QRect(560, 390, 91, 23))
        self.pushButton_Generate.setObjectName("pushButton_Generate")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 20, 51, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 50, 54, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 54, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_Mask = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Mask.setGeometry(QtCore.QRect(70, 50, 131, 22))
        self.comboBox_Mask.setObjectName("comboBox_Mask")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.comboBox_Mask.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 140, 54, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 54, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_UserName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_UserName.setGeometry(QtCore.QRect(70, 140, 131, 20))
        self.lineEdit_UserName.setObjectName("lineEdit_UserName")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(70, 170, 131, 20))
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.checkBox_Telnet = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Telnet.setGeometry(QtCore.QRect(380, 110, 61, 21))
        self.checkBox_Telnet.setChecked(True)
        self.checkBox_Telnet.setObjectName("checkBox_Telnet")
        self.pushButton_DeleteSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteSwitch.setGeometry(QtCore.QRect(560, 250, 91, 23))
        self.pushButton_DeleteSwitch.setObjectName("pushButton_DeleteSwitch")
        self.pushButton_Copy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Copy.setGeometry(QtCore.QRect(560, 430, 91, 23))
        self.pushButton_Copy.setObjectName("pushButton_Copy")
        self.textBrowser_Code = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Code.setGeometry(QtCore.QRect(10, 390, 541, 311))
        self.textBrowser_Code.setObjectName("textBrowser_Code")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_DeviceName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DeviceName.setGeometry(QtCore.QRect(70, 110, 131, 20))
        self.lineEdit_DeviceName.setObjectName("lineEdit_DeviceName")
        self.spinBox_PortNum = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_PortNum.setGeometry(QtCore.QRect(290, 110, 61, 22))
        self.spinBox_PortNum.setMinimum(10)
        self.spinBox_PortNum.setMaximum(99)
        self.spinBox_PortNum.setProperty("value", 52)
        self.spinBox_PortNum.setObjectName("spinBox_PortNum")
        self.spinBox_LocalVlan = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_LocalVlan.setGeometry(QtCore.QRect(290, 20, 61, 22))
        self.spinBox_LocalVlan.setMinimum(1)
        self.spinBox_LocalVlan.setMaximum(65535)
        self.spinBox_LocalVlan.setProperty("value", 10)
        self.spinBox_LocalVlan.setObjectName("spinBox_LocalVlan")
        self.spinBox_UplinkVlan = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_UplinkVlan.setGeometry(QtCore.QRect(290, 50, 61, 22))
        self.spinBox_UplinkVlan.setMinimum(1)
        self.spinBox_UplinkVlan.setMaximum(65535)
        self.spinBox_UplinkVlan.setProperty("value", 10)
        self.spinBox_UplinkVlan.setObjectName("spinBox_UplinkVlan")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 470, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_DesLocalVlan = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DesLocalVlan.setGeometry(QtCore.QRect(410, 20, 141, 20))
        self.lineEdit_DesLocalVlan.setObjectName("lineEdit_DesLocalVlan")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(380, 20, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(380, 50, 31, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_DesUplinkVlan = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DesUplinkVlan.setGeometry(QtCore.QRect(410, 50, 141, 20))
        self.lineEdit_DesUplinkVlan.setObjectName("lineEdit_DesUplinkVlan")
        self.lineEdit_DesUplinkPort = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DesUplinkPort.setGeometry(QtCore.QRect(410, 80, 141, 20))
        self.lineEdit_DesUplinkPort.setObjectName("lineEdit_DesUplinkPort")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(380, 80, 31, 21))
        self.label_13.setObjectName("label_13")
        self.textEdit_command = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_command.setGeometry(QtCore.QRect(290, 140, 261, 51))
        self.textEdit_command.setObjectName("textEdit_command")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(230, 150, 61, 21))
        self.label_14.setObjectName("label_14")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 510, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_SimpilyCode = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_SimpilyCode.setGeometry(QtCore.QRect(490, 110, 71, 21))
        self.checkBox_SimpilyCode.setChecked(True)
        self.checkBox_SimpilyCode.setObjectName("checkBox_SimpilyCode")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.setTest)
        self.pushButton_DeleteSwitch.clicked.connect(MainWindow.deleteTableItem)
        self.pushButton_AddSwitch.clicked.connect(MainWindow.addTableItem)
        self.tableWidget.itemDoubleClicked['QTableWidgetItem*'].connect(MainWindow.deleteTableItem)
        self.pushButton_Generate.clicked.connect(MainWindow.createCode)
        self.pushButton_Copy.clicked.connect(MainWindow.copyCode)
        self.pushButton_2.clicked.connect(MainWindow.clearCode)
        self.lineEdit_DesLocalVlan.editingFinished.connect(MainWindow.checkSameVlan)
        self.pushButton_3.clicked.connect(MainWindow.saveConfiguration)
        self.spinBox_LocalVlan.valueChanged['int'].connect(self.spinBox_UplinkVlan.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "代码生成器"))
        self.pushButton.setText(_translate("MainWindow", "测试按钮"))
        self.lineEdit_IP.setText(_translate("MainWindow", "10.54.1.250"))
        self.label.setText(_translate("MainWindow", "本 地 IP"))
        self.label_2.setText(_translate("MainWindow", "网    关 "))
        self.lineEdit_Gateway.setText(_translate("MainWindow", "10.54.1.254"))
        self.checkBox_Ssh.setText(_translate("MainWindow", "SSH"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "掩码"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "网关"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "端口数量"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "上联口"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telnet"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SSH"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "用户名"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "密码"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "本地vlan"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "上联vlan"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "设备名称"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "本地vlan描述"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "上联vlan描述"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "上联口描述"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "简化代码"))
        self.label_3.setText(_translate("MainWindow", "端口数量"))
        self.label_4.setText(_translate("MainWindow", "上 联 口"))
        self.lineEdit_UplinkPort.setText(_translate("MainWindow", "48 49 50 51 52"))
        self.pushButton_AddSwitch.setText(_translate("MainWindow", "添加交换机"))
        self.pushButton_Generate.setText(_translate("MainWindow", "生成代码"))
        self.label_5.setText(_translate("MainWindow", "本地vlan"))
        self.label_6.setText(_translate("MainWindow", "上联vlan"))
        self.label_7.setText(_translate("MainWindow", "掩    码"))
        self.comboBox_Mask.setItemText(0, _translate("MainWindow", "255.255.255.0"))
        self.comboBox_Mask.setItemText(1, _translate("MainWindow", "255.255.254.0"))
        self.comboBox_Mask.setItemText(2, _translate("MainWindow", "255.255.252.0"))
        self.comboBox_Mask.setItemText(3, _translate("MainWindow", "255.255.248.0"))
        self.comboBox_Mask.setItemText(4, _translate("MainWindow", "255.255.242.0"))
        self.comboBox_Mask.setItemText(5, _translate("MainWindow", "255.255.240.0"))
        self.comboBox_Mask.setItemText(6, _translate("MainWindow", "255.255.224.0"))
        self.comboBox_Mask.setItemText(7, _translate("MainWindow", "255.255.192.0"))
        self.comboBox_Mask.setItemText(8, _translate("MainWindow", "255.255.128.0"))
        self.comboBox_Mask.setItemText(9, _translate("MainWindow", "255.255.255.248"))
        self.comboBox_Mask.setItemText(10, _translate("MainWindow", "255.255.255.252"))
        self.comboBox_Mask.setItemText(11, _translate("MainWindow", "255.255.255.240"))
        self.comboBox_Mask.setItemText(12, _translate("MainWindow", "255.255.255.224"))
        self.comboBox_Mask.setItemText(13, _translate("MainWindow", "255.255.255.192"))
        self.comboBox_Mask.setItemText(14, _translate("MainWindow", "255.255.255.128"))
        self.label_8.setText(_translate("MainWindow", "用 户 名"))
        self.label_9.setText(_translate("MainWindow", "密    码"))
        self.lineEdit_UserName.setText(_translate("MainWindow", "admin"))
        self.lineEdit_Password.setText(_translate("MainWindow", "gjnet789"))
        self.checkBox_Telnet.setText(_translate("MainWindow", "Telnet"))
        self.pushButton_DeleteSwitch.setText(_translate("MainWindow", "删除交换机"))
        self.pushButton_Copy.setText(_translate("MainWindow", "复制代码"))
        self.label_10.setText(_translate("MainWindow", "设备名称"))
        self.lineEdit_DeviceName.setText(_translate("MainWindow", "SW_OA_Name"))
        self.pushButton_2.setText(_translate("MainWindow", "清空代码"))
        self.lineEdit_DesLocalVlan.setText(_translate("MainWindow", "Local"))
        self.label_11.setText(_translate("MainWindow", "描述"))
        self.label_12.setText(_translate("MainWindow", "描述"))
        self.lineEdit_DesUplinkVlan.setText(_translate("MainWindow", "Uplink Vlan"))
        self.lineEdit_DesUplinkPort.setText(_translate("MainWindow", "Uplink Port"))
        self.label_13.setText(_translate("MainWindow", "描述"))
        self.textEdit_command.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">添加命令</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "另存为"))
        self.checkBox_SimpilyCode.setText(_translate("MainWindow", "简化代码"))

